### ISSUE TITLE
Database error message not in stack trace

### ISSUE THREAD

**Issue by rosscoleman** [pacman82/arrow-odbc-py#45]
I discovered this at the same time as
https://github.com/pacman82/arrow-odbc/issues/63

DB2 on IBM i error messages and status codes aren't making it into the Python stack trace. I redacted some connection details below.

```python
from arrow_odbc import read_arrow_batches_from_odbc, insert_into_table
import getpass
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

dev_libl = ",REDACTEDLIB1,REDACTEDLIB2,REDACTEDLIB3"
driver = "{IBM i Access ODBC Driver 64-bit}"
dev_host="<redacted>"
user = getpass.getuser()
pwd = getpass.getpass()

# https://www.ibm.com/docs/en/i/7.4?topic=details-connection-string-keywords
dev_conn_str = f"DRIVER={driver};SYSTEM={dev_host};CMT=0;NAM=1;DBQ={dev_libl};UID={user};PWD={pwd}"

def write_to_db():
    arrow_table = pa.Table.from_arrays((np.arange(100), np.random.rand(100)), names=('row_num', 'rand_float'))
    print(arrow_table.schema)
    print(arrow_table.shape)
    reader = pa.RecordBatchReader.from_batches(arrow_table.schema, arrow_table.to_batches())
    insert_into_table(
        connection_string=dev_conn_str,
        chunk_size=10000,
        table="TSTPANDAS",
        reader=reader
    )

write_to_db()
```

I get this error
```
$ python arrow_odbc_test_minimal.py 
Password: 
row_num: int64
rand_float: double
(100, 2)
Traceback (most recent call last):
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/arrow_odbc_test_minimal.py", line 28, in <module>
    write_to_db()
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/arrow_odbc_test_minimal.py", line 21, in write_to_db
    insert_into_table(
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/.venv/lib/python3.9/site-packages/arrow_odbc/writer.py", line 140, in insert_into_table
    raise_on_error(error)
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/.venv/lib/python3.9/site-packages/arrow_odbc/error.py", line 30, in raise_on_error
    raise Error(error_out)
arrow_odbc.error.Error: An error occurred preparing SQL statement: INSERT INTO TSTPANDAS (row_num, rand_float) VALUES (?, ?);
```

I know from the other linked issue that the issue is ODBC drivers rejecting the semicolon at the end of the INSERT statement. So, I'm missing the database error message that `pyodbc` wraps like this:
```
pyodbc.ProgrammingError: ('42000', '[42000] [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token ; was not valid. Valid tokens: <END-OF-STATEMENT>. (-104) (SQLPrepare)')
```

**Comment by rosscoleman** [comment]
I added
```
arrow_odbc.log_to_stderr(1)
```

That does work, though I don't see a way to redirect it to Python logging instead of stderr.

```
$ python arrow_odbc_test_minimal.py 
Password: 
row_num: int64
rand_float: double
(100, 2)
WARN - State: 01000, Native error: 0, Message: [unixODBC][Driver Manager]Driver does not support the requested version
WARN - State: 42000, Native error: -104, Message: [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token ; was not valid. Valid tokens: <END-OF-STATEMENT>.
Traceback (most recent call last):
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/arrow_odbc_test_minimal.py", line 30, in <module>
    write_to_db()
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/arrow_odbc_test_minimal.py", line 22, in write_to_db
    insert_into_table(
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/.venv/lib/python3.9/site-packages/arrow_odbc/writer.py", line 140, in insert_into_table
    raise_on_error(error)
  File "/data/hub/rcoleman12/ic-ml-hard-part-adds/.venv/lib/python3.9/site-packages/arrow_odbc/error.py", line 30, in raise_on_error
    raise Error(error_out)
arrow_odbc.error.Error: An error occurred preparing SQL statement: INSERT INTO TSTPANDAS (row_num, rand_float) VALUES (?, ?);
```

**Comment by pacman82** [comment]
Hello @rosscoleman ,

`arrow-odbc-py` uses the `Display` trait to generate the error message ending up in the Python exception. I could switch to the `Debug` trait to catch the entire error, yet this would also get rid of some of the aspects which make the exception more human readable.

I feel the conceptional error is not in `arrow-odbc-py` but in `arrow-odbc`. The motivation to translate the original error to begin with, was to include the SQL statement which causes the syntax error to the context, not hide or wrap the original one.

Thanks for pointing this out and sorry for the extra debugging you had to do because of the translation.

Best, Markus

**Comment by pacman82** [comment]
Hello @rosscoleman ,

started release for `arrow-odbc-py 1.2.1` which does no longer hide the original error emitted by the ODBC database driver.

Best, Markus

**Comment by rosscoleman** [comment]
@pacman82, thanks for this! I like how it is working.

```
(venv) ross@ross-T480-linux:~/git/db2_pyodbc$ python ibmi_arrow_odbc.py 
Password: 
   MYINT  MYFLOAT
0      2      0.2
Traceback (most recent call last):
  File "/home/ross/git/db2_pyodbc/ibmi_arrow_odbc.py", line 48, in <module>
    main()
  File "/home/ross/git/db2_pyodbc/ibmi_arrow_odbc.py", line 45, in main
    dataframe_to_table(df)
  File "/home/ross/git/db2_pyodbc/ibmi_arrow_odbc.py", line 31, in dataframe_to_table
    insert_into_table(
  File "/home/ross/git/db2_pyodbc/venv/lib/python3.10/site-packages/arrow_odbc/writer.py", line 140, in insert_into_table
    raise_on_error(error)
  File "/home/ross/git/db2_pyodbc/venv/lib/python3.10/site-packages/arrow_odbc/error.py", line 30, in raise_on_error
    raise Error(error_out)
arrow_odbc.error.Error: An error occurred preparing SQL statement. SQL:
INSERT INTO raclibdw.mytable (myint, myfloat) VALUES (?, ?);
ODBC emitted an error calling 'SQLPrepare':
State: 42000, Native error: -104, Message: [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token ; was not valid. Valid tokens: <END-OF-STATEMENT>.
```
