### ISSUE TITLE
DB2: Invalid attribute value, function: "SQLSetEnvAttr"

### ISSUE THREAD

**Issue by tomsej** [pacman82/arrow-odbc-py#60]
Hi, thanks a lot for this awesome lib. I am having a problem with connecting to the DB2. I have setup the container (based on `public.ecr.aws/lambda/python:3.10`) where I installed DB ODBC client (with `ibm_db`). If I try `isql` or `pyodbc` everything works fine:
```
# isql -k -v "DSN=DB2;database=xxx;hostname=xxx;port=50001;uid=xxx;pwd=xxx"
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
```
or
```
>>> import pyodbc
>>> con = pyodbc.connect("DSN=DB2;database=xxx;hostname=xxx;port=50001;uid=xxx;pwd=xxx")
... querying works fine
```
But when I run `arrow-odbc`:
```
from arrow_odbc import read_arrow_batches_from_odbc
read_arrow_batches_from_odbc("SELECT * FROM xxx", connection_string="DSN=DB2;database=xxx;hostname=xxx;port=50001;uid=xxx;pwd=xxx", batch_size=10000)
```
I get a following error:
```
thread '<unnamed>' panicked at src/lib.rs:24:54:
called `Result::unwrap()` on an `Err` value: Diagnostics { record: State: S1009, Native error: 0, Message: [unixODBC][Driver Manager]Invalid attribute value, function: "SQLSetEnvAttr" }
stack backtrace:
   0:       0x40097ff1f0 - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:       0x40097ff1f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:       0x40097ff1f0 - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:       0x40097ff1f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:       0x40097acfac - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:       0x40097acfac - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:       0x40097d3c1d - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:       0x40098007ae - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:       0x40098007ae - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:       0x4009800390 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:       0x40098013b1 - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:       0x40098013b1 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:       0x4009800e82 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:       0x4009800de6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:       0x4009800dd1 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:       0x400971c162 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:       0x400971c599 - core::result::unwrap_failed::hccb456d39e9c31fc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:       0x400971b3d2 - std::sys_common::once::futex::Once::call::h892ebff3825980de
  18:       0x400978aba5 - arrow_odbc_connect_with_connection_string
  19:       0x40096de052 - ffi_call_unix64
  20:       0x40096dd12c - ffi_call_int
  21:       0x40096db01f - cdata_call
                               at /project/src/c/_cffi_backend.c:3201:5
  22:       0x4000b8efa1 - _PyObject_MakeTpCall
                               at /var/python-src/Objects/call.c:215
  23:       0x4000c05b4e - _PyObject_VectorcallTstate
                               at /var/python-src/./Include/cpython/abstract.h:112
  24:       0x4000c05b4e - PyObject_Vectorcall
                               at /var/python-src/./Include/cpython/abstract.h:123
  25:       0x4000c05b4e - call_function
                               at /var/python-src/Python/ceval.c:5893
  26:       0x4000c05b4e - _PyEval_EvalFrameDefault
                               at /var/python-src/Python/ceval.c:4181
  27:       0x4000bfe212 - _PyEval_EvalFrame
                               at /var/python-src/./Include/internal/pycore_ceval.h:46
  28:       0x4000bfe212 - _PyEval_Vector
                               at /var/python-src/Python/ceval.c:5067
  29:       0x4000bff3d6 - _PyObject_VectorcallTstate
                               at /var/python-src/./Include/cpython/abstract.h:114
  30:       0x4000bff3d6 - PyObject_Vectorcall
                               at /var/python-src/./Include/cpython/abstract.h:123
  31:       0x4000bff3d6 - call_function
                               at /var/python-src/Python/ceval.c:5893
  32:       0x4000bff3d6 - _PyEval_EvalFrameDefault
                               at /var/python-src/Python/ceval.c:4213
  33:       0x4000bfe212 - _PyEval_EvalFrame
                               at /var/python-src/./Include/internal/pycore_ceval.h:46
  34:       0x4000bfe212 - _PyEval_Vector
                               at /var/python-src/Python/ceval.c:5067
  35:       0x4000c00365 - _PyObject_VectorcallTstate
                               at /var/python-src/./Include/cpython/abstract.h:114
  36:       0x4000c00365 - PyObject_Vectorcall
                               at /var/python-src/./Include/cpython/abstract.h:123
  37:       0x4000c00365 - call_function
                               at /var/python-src/Python/ceval.c:5893
  38:       0x4000c00365 - _PyEval_EvalFrameDefault
                               at /var/python-src/Python/ceval.c:4231
  39:       0x4000bfe212 - _PyEval_EvalFrame
                               at /var/python-src/./Include/internal/pycore_ceval.h:46
  40:       0x4000bfe212 - _PyEval_Vector
                               at /var/python-src/Python/ceval.c:5067
  41:       0x4000bfe03d - PyEval_EvalCode
                               at /var/python-src/Python/ceval.c:1134
  42:       0x4000c9920d - run_eval_code_obj
                               at /var/python-src/Python/pythonrun.c:1291
  43:       0x4000c9919c - run_mod
                               at /var/python-src/Python/pythonrun.c:1312
  44:       0x4000b2e87d - PyRun_InteractiveOneObjectEx
                               at /var/python-src/Python/pythonrun.c:277
  45:       0x4000b2ea35 - _PyRun_InteractiveLoopObject
                               at /var/python-src/Python/pythonrun.c:148
  46:       0x4000b2e4e7 - _PyRun_AnyFileObject
                               at /var/python-src/Python/pythonrun.c:84
  47:       0x4000b2eb30 - PyRun_AnyFileExFlags
                               at /var/python-src/Python/pythonrun.c:116
  48:       0x4000b3b091 - pymain_run_stdin
                               at /var/python-src/Modules/main.c:502
  49:       0x4000b3b091 - pymain_run_python
                               at /var/python-src/Modules/main.c:590
  50:       0x4000b3b091 - Py_RunMain
                               at /var/python-src/Modules/main.c:666
  51:       0x4000ca0a49 - Py_BytesMain
                               at /var/python-src/Modules/main.c:720
  52:       0x4001bb313a - __libc_start_main
  53:           0x40064a - _start
  54:                0x0 - <unknown>
  ```
  
  Any idea what can be wrong?
  
### Settings
 **Python:** 3.10.13
 **arrow-odbc-py:**: 1.3.0
 **unixODBC**: 2.3.1
 

**/etc/odbcinst.ini** 
```
[DB2 Driver]
Description = DB2 Driver
Driver      = /var/lang/lib/python3.10/site-packages/clidriver/lib/libdb2.so
FileUsage   = 1
DontDLClose = 1
```

**/etc/odbc.ini**
```
[DB2]
Driver = DB2 Driver
```

**Comment by pacman82** [comment]
Hello @tomsej 

> thanks a lot for this awesome lib

Well thank you. Sorry it does not work for you at the moment.

It actually crashes than creating the ODBC environment this is even before anything driver or database related would happen. Just to verify: Do you have Connection pooling enabled?

Also, the unixODBC version is 13 years old. I have no idea if that is even supposed to work. Could you update it?

Best, Markus

**Comment by pacman82** [comment]
In case my assumption is correct and declaring the ODBC API version fails due to an outdated version of unixODBC you would now receive a better error, if you update to `arrow-odbc 1.3.2`.

**Comment by pacman82** [comment]
Please feel free to reopen the issue if you neither see the better error, or an update to a newer version of unixODBC does not get `arrow-odbc` to work

**Comment by tomsej** [comment]
Thank you @pacman82 for quick answer, you are right! It was really the problem of old unixODBC. I was really not expecting that there  is so much differences between minor versions.

For everyone who is reading this and need update `unixODBC` in `public.ecr.aws/lambda/python:3.10`:

```
RUN yum update -y && \
    curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/yum.repos.d/mssql-release.repo && \
    yum remove unixODBC-utf16 unixODBC-utf16-devel && \
    yum install -y \
        # Otherwise ImportError: libpam.so.0: cannot open shared object file: No such file or directory
        pam \
        unixODBC-devel \
        && \
    yum clean all && \
    rm -rf /var/cache/yum
```

**Comment by pacman82** [comment]
You are welcome
